version: "3.9"

services:
  emailmessage-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emailmessage-api
    ports:
      - "9001:9001"
    environment:
      SPRING_RABBITMQ_HOST: clientes-rabbitmq  # Nome do container do RabbitMQ
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_VIRTUAL_HOST: /
    networks:
      - app-network  # Rede compartilhada com o RabbitMQ

networks:
  app-network:
    external: true  # Assume que a rede jรก foi criada pelo outro docker-compose